config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  resources :comments, only: [:edit, :create, :update, :destroy]
  resources :blog_posts
  devise_for :users
  resources :users, except: [:create, :edit, :update]

  # get 'user/set_blog_post'
  # get 'user/blog_post_params'
  get 'blog_posts' => 'blog_posts#index'
  get 'show_job' => 'jobs#show'
  get 'schedule' => 'users#schedule'

  post 'create_user' => 'users#create', as: :create_user
  get 'edit_user' => 'users#edit', as: :edit_user
  get 'show_user' => 'users#show', as: :show_user
  patch 'users/:id' => 'users#update', as: :update_user

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  has_and_belongs_to_many :users, dependent: :destroy
  serialize :workers, Array

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :add_worker, :remove_worker]
  before_action :authenticate_user!
  before_action :calender, only: :index

  authorize_resource

  include JobsHelper

  # GET /jobs
  def index
    @jobs = Job.all
  end

  def calender

    @calender_days = []
    current_time = Date.parse(params[:current_time])

    month_sub_one = current_time.month - 1
    month_add_one = current_time.month + 1

    # finds the first day of the calender for the current month
    until (current_time.strftime('%A') == 'Sunday') && (current_time.day == 1 || current_time.month == month_sub_one)
      if current_time.day == 1
        current_time = current_time.advance(months: -1)
        current_time = current_time.change(day: Time.days_in_month(current_time.month))
      end
      current_time = current_time.advance(days: -1)
    end

    # fills calender for current month
    until @calender_days.length == 35
      @calender_days.push(current_time)
      current_time = current_time.advance(days: 1)
    end

  end

  # GET /jobs/1
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /jobs/1
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /jobs/1
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url(current_time: Time.now), notice: 'Job was successfully destroyed.' }
    end
  end

  private
    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:name, :datetime, :created_by, :client_id, :notes, :workers)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def create_client_set(date)
    client_set = Set[]

    @jobs.where('DATE(datetime) = ?', Date.parse(date.to_s)).each do |job|
      client_set.add(job.client_id)
    end

    return client_set.to_a

  end

end

app/views/jobs/_day.html.erb
<% if date.strftime('%Y/%m/%d') == Time.now.strftime('%Y/%m/%d') %>
  <button type="button" class="align-text-bottom btn btn-warning btn-xs" data-toggle="modal" data-target="#day-tasks-<%= count %>">
    <%= date.strftime('%d') %>
  </button>
<% else %>
  <button type="button" class="align-text-bottom btn btn-primary btn-xs" data-toggle="modal" data-target="#day-tasks-<%= count %>">
    <%= date.strftime('%d') %>
  </button>
<% end %>
<div class="modal fade" id="day-tasks-<%= count %>" tabindex="-1" role="dialog" aria-labelledby="day-tasks-Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="day-tasks-ModalLabel"><%= date.strftime('%m/%d') %></h4>
      </div>
      <div class="modal-body">
        <% client_set.each do |client| %>
          <h4><%= link_to User.find(client).name, show_user_path(id: User.find(client).id) %></h4>
          <% @jobs.where("client_id = ? AND DATE(datetime) = ?", User.find(client).id, Date.parse(date.to_s)).order(:datetime).each do |job| %>
            <u>Job Name:</u> <%= link_to job.name, show_job_path(id: job.id) %><br />
            <u>Address:</u> <%= get_address(User.find(job.client_id)) %><br />
            <u>Time:</u> <%= job.datetime.strftime('%I:%M%P') %><br />
            <u>Created</u> By: <%= User.find(job.created_by).username %><br />
            <u>Notes:</u> <%= job.notes %><br />
            <u>Workers:</u><br />
            <% job.workers.each do |worker| %><%= User.find(worker).name %><br /><% end %>
          <% end %>
          <hr />
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="align-text-bottom btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :job_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <strong>Date and Time</strong><br />
    <%= form.datetime_select :datetime, id: :job_datetime, class: "form-control" %>
  </div>

  <%= form.hidden_field :created_by, value: current_user.id %>

  <div class="form-group">
    <%= form.label :client_id %>
    <%= form.collection_select(:client_id, User.where(role: "client"), :id, :name) %>
  </div>

  <p>
    <strong>Workers:</strong><br />
    <% @job.workers.each do |worker| %>
      <%= link_to User.find(worker).name, remove_worker_path(id: worker) %><br />
    <% end %>
  </p>

  <div class="form-group">
    <%= form.label :workers %>
    <%= form.collection_select(:workers, User.where(role: "worker"), :id, :name) %>
  </div>

  <div class="form-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :job_notes, rows: 5, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="white-background">
  <h1>Editing Job</h1>

  <%= render 'form', job: @job %>
</div>

app/views/jobs/index.html.erb
<div class="white-background">
  <p id="notice"><%= notice %></p>

  <h2>
    <%= link_to jobs_path(current_time: @calender_days[15].advance(months: -1)) do %>
      <span class="glyphicon glyphicon-chevron-left"></span>
    <% end %>
    <%= @calender_days[15].strftime('%B') %>
    <%= link_to jobs_path(current_time: @calender_days[15].advance(months: 1)) do %>
      <span class="glyphicon glyphicon-chevron-right"></span>
    <% end %>
  </h2>

  <div class="calender">
    <table class="table">
      <thead>
        <tr>
          <th>Sunday</th>
          <th>Monday</th>
          <th>Tuesday</th>
          <th>Wednesday</th>
          <th>Thursday</th>
          <th>Friday</th>
          <th>Saturday</th>
        </tr>
      </thead>
      <tbody>
        <% count = 0 %>
        <% 5.times do %>
          <tr>
            <% 7.times do %>
              <td>
                <% date = @calender_days[count] %>
                <% client_set = create_client_set(date) %>
                <%= render partial: 'day', locals: {jobs: @jobs, count: count, date: date, client_set: client_set} %>
                <% client_set[0..2].each do |client| %>
                  <%= link_to User.find(client).name, show_user_path(id: User.find(client).id) %><br />
                <% end %>
                <% if client_set.length > 3 %>
                  <p class="center-text">+ <%= client_set.length - 3 %> More</p>
                <% end %>
                <% count += 1 %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br />

  <%= link_to 'New Job', new_job_path, class: "btn btn-default" %>
</div>

app/views/jobs/new.html.erb
<div class="white-background">
  <h1>New Job</h1>

  <%= render 'form', job: @job %>
</div>

app/views/jobs/show.html.erb
<div class="white-background">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Job Name:</strong>
    <%= @job.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @job.datetime.strftime('%Y/%m/%d - %I:%M%P') %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= User.find(@job.created_by).username %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= link_to User.find(@job.client_id).name, show_user_path(id: @job.client_id) %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @job.notes %>
  </p>

  <p>
    <strong>Workers:</strong><br />
    <% @job.workers.each do |worker| %>
      <%= User.find(worker).name %><br />
    <% end %>
  </p>

  <%= link_to 'Edit', edit_job_path(@job), class: "btn btn-warning" %>
  <%= link_to 'Destroy', @job, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>