config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  resources :comments, only: [:edit, :create, :update, :destroy]
  resources :blog_posts
  devise_for :users
  resources :users, except: [:create, :edit, :update]

  # get 'user/set_blog_post'
  # get 'user/blog_post_params'
  get 'blog_posts' => 'blog_posts#index'
  get 'show_job' => 'jobs#show'
  get 'schedule' => 'users#schedule'

  post 'create_user' => 'users#create', as: :create_user
  get 'edit_user' => 'users#edit', as: :edit_user
  get 'show_user' => 'users#show', as: :show_user
  patch 'users/:id' => 'users#update', as: :update_user

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :set_default

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_posts, dependent: :destroy
  has_many :comment
  has_and_belongs_to_many :jobs

  validates :username, presence: true, uniqueness: true

  mount_uploader :avatar, AvatarUploader

  def set_default
    if self.role == nil || self.role == ""
      self.role = "client"
    end
  end

  def admin?
   role == "admin"
  end

  def manager?
   role == "manager"
  end

  def worker?
   role == "worker"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :schedule]
  before_action :authenticate_user!
  before_action :authorize_admin, only: [:create, :edit, :update]

  authorize_resource

  include UserHelper

  # GET /users
  def index
    @users = User.all
  end

  # creates array filled with job objects for specific worker
  def schedule
    @jobs = []
    @current_week = Time.now

    until @current_week.strftime('%A') == 'Sunday' do
      @current_week = @current_week.advance(days: -1)
    end

    Job.all.order(:datetime).each do |job|
      if job.workers.include?(@user.id)
        if job.datetime > @current_week.at_beginning_of_day() && job.datetime < @current_week.advance(days: 6).at_end_of_day()
          @jobs.push(job)
        end
      end
    end

  end

  # GET /users/1
  def show
    @jobs = Job.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path(@user), notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path(@user), notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role, :name, :street, :city, :zip, :state, :username, :avatar, :phone)
    end
end

app/helpers/user_helper.rb
module UserHelper

  private

  def authorize_admin
    return unless !current_user.admin?
    redirect_to root_path, alert: 'Admins only!'
  end

end

app/views/users/edit.html.erb
<div class="white-background">
  <%= form_for @user do |form| %>

    <div class="form-group">
      <%= form.label :name %><br />
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :username %><br />
      <%= form.text_field :username, autofocus: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %><br />
      <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group input-medium bfh-phone">
      <%= form.label :phone %><br />
      <%= form.text_field :phone, class: "form-control "%>
    </div>

    <% if current_user.admin? %>
      <div class="form-group">
        <%= form.label :role %><br />
        <%= form.text_field :role, class: "form-control" %>
      </div>
    <% end %>

    <div class="row">
      <div class="col-sm-5 form-group">
        <%= form.label :street %><br />
        <%= form.text_field :street, class: "form-control" %>
      </div>

      <div class="col-sm-3 form-group">
        <%= form.label :city %><br />
        <%= form.text_field :city, class: "form-control" %>
      </div>

      <div class="col-sm-2 form-group">
        <%= form.label :zip %><br />
        <%= form.text_field :zip, class: "form-control" %>
      </div>

      <div class=" col-sm-2 form-group">
        <%= form.label :state %><br />
        <%= form.text_field :state, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <strong>Upload a Profile Pic: </strong>
      <%= form.file_field :avatar, class: "form-control-file" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= form.password_field :password, autocomplete: "off", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %><br />
      <%= form.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
    </div>

    <span class="actions">
      <%= form.submit "Edit", class: "btn btn-warning" %>
    </span>

    <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger float-right" %>

  <% end %>
</div>

app/views/users/index.html.erb
<div class="white-background">
  <table class="table">
      <thead>
        <tr>
          <th>Role</th>
          <th>Email</th>
          <th>Username</th>
          <th>Name</th>
          <th colspan="4">Address</th>
        </tr>
      </thead>
      <tbody>
        <% @users.where.not(role: "admin").each do |user| %>
          <tr>
            <td><%= user.role %></td>
            <td><%= link_to user.email, edit_user_path(id: user.id) %></td>
            <td><%= user.username %></td>
            <td><%= link_to user.name, show_user_path(id: user.id) %></td>
            <% if user.street == nil || user.city == nil || user.state == nil || user.zip == nil %>
              <td></td>
            <% else %>
              <td><%= get_address(user) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
  </table>

  <%= link_to "Create User", new_user_path, class: "btn btn-default" %>

</div>

app/views/users/new.html.erb
<div class="white-background">
  <%= form_for User.new, url: create_user_path do |form| %>

    <div class="form-group">
      <%= form.label :name %><br />
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :username %><br />
      <%= form.text_field :username, autofocus: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %><br />
      <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group input-medium bfh-phone">
      <%= form.label :phone %><br />
      <%= form.text_field :phone, class: "form-control "%>
    </div>

    <% if current_user.admin? %>
      <div class="form-group">
        <%= form.label :role %><br />
        <%= form.text_field :role, class: "form-control" %>
      </div>
    <% end %>

    <div class="row">
      <div class="col-sm-5 form-group">
        <%= form.label :street %><br />
        <%= form.text_field :street, class: "form-control" %>
      </div>

      <div class="col-sm-3 form-group">
        <%= form.label :city %><br />
        <%= form.text_field :city, class: "form-control" %>
      </div>

      <div class="col-sm-2 form-group">
        <%= form.label :zip %><br />
        <%= form.text_field :zip, class: "form-control" %>
      </div>

      <div class=" col-sm-2 form-group">
        <%= form.label :state %><br />
        <%= form.text_field :state, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <strong>Upload a Profile Pic: </strong>
      <%= form.file_field :avatar, class: "form-control-file" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= form.password_field :password, autocomplete: "off", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %><br />
      <%= form.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
    </div>

    <div class="actions">
      <%= link_to 'Back', users_path, class: "btn btn-default" %>
    </div>

    <%= form.submit "Sign up", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/users/schedule.html.erb
<div class="white-background">
  <table class="table weekly_schedule">
    <thead>
      <tr><h3 class="center-text">Week of <%= @current_week.strftime('%m/%d') %> - <%= @current_week.advance(days: 6).strftime('%m/%d') %></h3></tr>
      <tr>
        <th>Sunday</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Saturday</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% 7.times do |n| %>
          <td>
            <% @jobs.each do |job| %>
              <% if @current_week.advance(days: n).strftime('%A') == job.datetime.strftime('%A') %>
                <div class="appointment">
                  <%= User.find(job.client_id).name %><br />
                  <%= job.datetime.strftime('%I:%M%P') %><br />
                  <%= link_to job.name, show_job_path(id: job.id) %><br />
                  <strong>Workers:</strong><br />
                  <% job.workers.each do |worker| %>
                    <% if User.find(worker).id == current_user.id %>
                      <div class="highlight">
                        <%= User.find(worker).name %><br />
                      </div>
                    <% else %>
                      <%= User.find(worker).name %><br />
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="white-background">
  <h4><%= @user.name %></h4>
  <h5><%= get_address(@user) %></h5>
  <% @jobs.where(client_id: @user.id).order(:datetime).each do |job| %>
    <% if job.datetime.strftime('%Y/%m/%d') == Time.now.strftime('%Y/%m/%d')%>
      <p class="highlight"><strong><span class="monospace-font"><%= job.datetime.strftime('%Y/%m/%d - %I:%M%P') %></span></strong>&nbsp&nbsp<%= link_to job.name, show_job_path(id: job.id) %></p>
    <% else %>
      <p><strong><span class="monospace-font"><%= job.datetime.strftime('%Y/%m/%d - %I:%M%P') %></span></strong>&nbsp&nbsp<%= link_to job.name, show_job_path(id: job.id) %></p>
    <% end %>
  <% end %>
</div>