config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  resources :comments, only: [:edit, :create, :update, :destroy]
  resources :blog_posts
  devise_for :users
  resources :users, except: [:create, :edit, :update]

  # get 'user/set_blog_post'
  # get 'user/blog_post_params'
  get 'blog_posts' => 'blog_posts#index'
  get 'show_job' => 'jobs#show'
  get 'schedule' => 'users#schedule'

  post 'create_user' => 'users#create', as: :create_user
  get 'edit_user' => 'users#edit', as: :edit_user
  get 'show_user' => 'users#show', as: :show_user
  patch 'users/:id' => 'users#update', as: :update_user

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_contact.html.erb
<div class="contact">
  <div class="custom-button">
    <!-- make contact us page -->
    <p><a href="#">Contact Us</a></p>
  </div>
  <div class="social-buttons">
    <div class="facebook">
      <a href="https://www.facebook.com/MaidYourVVay/?ref=br_rs"><%= image_tag "social/facebook.png" %></a>
    </div>
    <div class="twitter">
      <a href="#"><%= image_tag "social/twitter.png" %></a>
    </div>
    <div class="linkedin">
      <a href="#"><%= image_tag "social/linkedin.png" %></a>
    </div>
</div>

app/views/layouts/_demo.html.erb
<button type="button" class="navbar-btn btn btn-danger btn-sm" data-toggle="modal" data-target="#demo" data-backdrop="false">
  Demo Users
</button>
<div class="modal fade" id="demo" tabindex="-1" role="dialog" aria-labelledby="demo-Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="demo-ModalLabel">Welcome!</h4>
      </div>
      <div class="modal-body">
        <p>
          Welcome to my demo site (work in progress)! Please use any of the emails (all passwords are "password") below to login and see the sites features. I suggest try the Admin and Worker users to see all the features. Source code can be found on my <a style="color: blue;" href="https://github.com/gjaros/maidyourway">github</a>!
        </p>
        <p><strong>Admin:</strong> admin@maidyourway</p>
        <p><strong>Manager:</strong> manager@maidyourway</p>
        <p><strong>Worker:</strong> <%= User.where(role: "worker").sample.email %></p>
        <p><strong>Client:</strong> <%= User.where(role: "client").sample.email %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<nav class="custom-footer">
  <p>Copyright Maid Your Way&copy; 2018</p>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MYW", blog_posts_path, class: "navbar-brand", size: 50 %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= render 'layouts/demo' %></li>
        <% if signed_in? && current_user.role == "admin" %>
          <li><%= link_to "Manage Users", users_path %></li>
        <% end %>
        <% if signed_in? && current_user.role == "worker" %>
          <li><%= link_to "Schedule", schedule_path(id: current_user.id) %></li>
        <% end %>
        <% if signed_in? && current_user.role != "client" %>
          <li><%= link_to "Calender", jobs_path(current_time: Time.now) %></li>
        <% end %>
        <% if current_user %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to current_user.username, edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maidyourway</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="my-background">

    <%= render "layouts/navbar" %>

    <div id="flash">
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type) %> fade-in">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <!-- <%= render 'layouts/footer' %> -->

  </body>

</html>